package com.yshanginfo.framwork.sys.entity;

// Generated 2014-8-26 14:05:09 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.yshanginfo.framwork.core.entity.IdEntity;

/**
 * CommDictionary generated by hbm2java
 */
@Entity
@Table(name = "sys_dictionary")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Dictionary extends IdEntity {

	private DictionaryType dictionaryType;
	private String name;
	private String code;
	private String value;
	private Integer orderId;
	private String extend1;
	private String extend2;
	private String extend3;
	private String memo;

	public Dictionary() {
	}

	public Dictionary(String id, DictionaryType dictionaryType, String name,
			String code, String value, String extend1, String extend2,
			String extend3, String memo) {
		this.id = id;
		this.dictionaryType = dictionaryType;
		this.name = name;
		this.code = code;
		this.value = value;
		this.extend1 = extend1;
		this.extend2 = extend2;
		this.extend3 = extend3;
		this.memo = memo;
	}



	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dictionary_type_id")
	public DictionaryType getDictionaryType() {
		return this.dictionaryType;
	}

	public void setDictionaryType(DictionaryType dictionaryType) {
		this.dictionaryType = dictionaryType;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
    @Column(name="order_id")
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

	@Column(name = "extend_1")
	public String getExtend1() {
		return this.extend1;
	}

	public void setExtend1(String extend1) {
		this.extend1 = extend1;
	}

	@Column(name = "extend_2")
	public String getExtend2() {
		return this.extend2;
	}

	public void setExtend2(String extend2) {
		this.extend2 = extend2;
	}

	@Column(name = "extend_3")
	public String getExtend3() {
		return this.extend3;
	}

	public void setExtend3(String extend3) {
		this.extend3 = extend3;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
