package com.yshanginfo.framwork.sys.entity;

// Generated 2014-8-26 14:05:09 by Hibernate Tools 3.2.2.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.yshanginfo.framwork.core.entity.IdEntity;

/**
 * DictionaryType generated by hbm2java
 */
@Entity
@Table(name = "sys_dictionary_type")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class DictionaryType extends IdEntity {

	private String name;
	private String code;
	private String memo;
	@JsonIgnore
	private List<Dictionary> dictionaries = new ArrayList<Dictionary>(0);

	public DictionaryType() {
	}

	public DictionaryType(String id, String name, String code, String memo,
			List<Dictionary> dictionaries) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.memo = memo;
		this.dictionaries = dictionaries;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "memo")
	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dictionaryType")
	public List<Dictionary> getDictionaries() {
		return this.dictionaries;
	}

	public void setDictionaries(List<Dictionary> dictionaries) {
		this.dictionaries = dictionaries;
	}

}
