package com.yshanginfo.framwork.sys.entity;

// Generated 2014-6-19 17:25:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yshanginfo.framwork.core.entity.IdEntity;

/**
 * RoleAuth generated by hbm2java
 */
@Entity
@Table(name = "sys_role_auth")
public class RoleAuth  extends IdEntity {

	
	private Role role;
	private Resource resource;
	private String permissionIds;

	public RoleAuth() {
	}

	public RoleAuth(String id) {
		this.id = id;
	}

	public RoleAuth(String id, Role role, Resource resource, String permissionIds) {
		this.id = id;
		this.role = role;
		this.resource = resource;
		this.permissionIds = permissionIds;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	@JsonIgnore
	public Role getRole() {
		return this.role;
	}

	@JsonDeserialize
	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "resource_id")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@Column(name = "permission_ids")
	public String getPermissionIds() {
		return this.permissionIds;
	}

	public void setPermissionIds(String permissionIds) {
		this.permissionIds = permissionIds;
	}

}
